name: thenewboston_sdk
description: An unofficial SDK to interact with the TNB cryptocurrency server nodes.
version: 0.0.1
# homepage: https://www.example.com

analyzer:
  - enable-experiment:
      - non-nullable

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.1
  cryptography: ^2.0.1
  hex: ^0.2.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  json_serializable: ^4.1.0
  build_runner: ^1.12.2
